# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Valence < Formula
  desc "Targeted wordlist generator for authorized security audits and pentests"
  homepage "https://github.com/g4m3m4g/Valence"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/g4m3m4g/Valence/releases/download/v1.0.1/valence_darwin_amd64.tar.gz"
      sha256 "edccf008edc3eccb590ba1eb6636bf49e1072680b053bab9868ed171af7ef88b"

      define_method(:install) do
        bin.install "valence"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/g4m3m4g/Valence/releases/download/v1.0.1/valence_darwin_arm64.tar.gz"
      sha256 "e5bfd8a211c182a14ee5f6d87c85d6b5f78d9528b9140f0b5ad01dca61711bb2"

      define_method(:install) do
        bin.install "valence"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/g4m3m4g/Valence/releases/download/v1.0.1/valence_linux_amd64.tar.gz"
      sha256 "9193b095fe71806b7ab4cb8455df9ab19abfffb83a663dbff6e53227ddf77001"
      define_method(:install) do
        bin.install "valence"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/g4m3m4g/Valence/releases/download/v1.0.1/valence_linux_arm64.tar.gz"
      sha256 "74583f70ef46ce1d6724c5a1a877f421aa8b8ce29d06280058849f7699e96b68"
      define_method(:install) do
        bin.install "valence"
      end
    end
  end

  test do
    system "#{bin}/valence", "--help"
  end
end
