# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Valence < Formula
  desc "Targeted wordlist generator for authorized security audits and pentests"
  homepage "https://github.com/g4m3m4g/Valence"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/g4m3m4g/Valence/releases/download/v0.1.0/valence_darwin_amd64.tar.gz"
      sha256 "ecff19ec40525ce024626ce9930775cddc1057689d31960e1fadafc898b1a8a2"

      define_method(:install) do
        bin.install "valence"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/g4m3m4g/Valence/releases/download/v0.1.0/valence_darwin_arm64.tar.gz"
      sha256 "dce16edb050f6a44545bf5cdf4016000e98d281e5f8777c9faa8566b80ccc997"

      define_method(:install) do
        bin.install "valence"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/g4m3m4g/Valence/releases/download/v0.1.0/valence_linux_amd64.tar.gz"
      sha256 "fb5fecf27979ba75a229ea7cb9e1661fdd46dda8595207add4d3407d1b594906"
      define_method(:install) do
        bin.install "valence"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/g4m3m4g/Valence/releases/download/v0.1.0/valence_linux_arm64.tar.gz"
      sha256 "c7cd88c550935e5d77f337ba00ac93178b6c19f406a0fac3820873f55657d3a0"
      define_method(:install) do
        bin.install "valence"
      end
    end
  end

  test do
    system "#{bin}/valence", "--help"
  end
end
