# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Valence < Formula
  desc "Targeted wordlist generator for authorized security audits and pentests"
  homepage "https://github.com/g4m3m4g/Valence"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/g4m3m4g/Valence/releases/download/v1.0.0/valence_darwin_amd64.tar.gz"
      sha256 "28ccfb1482adbf17996fc24954e6aad3724c8a7fab3a2b38f00692d66d0aa6f7"

      define_method(:install) do
        bin.install "valence"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/g4m3m4g/Valence/releases/download/v1.0.0/valence_darwin_arm64.tar.gz"
      sha256 "552b735ebe7a62c2ba859efb21432cca8250c93a408d42b31fe1a672f6ffac85"

      define_method(:install) do
        bin.install "valence"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/g4m3m4g/Valence/releases/download/v1.0.0/valence_linux_amd64.tar.gz"
      sha256 "d76746efb4e4cf05d873212f2fcd3249867f4509aab35e0d871055e91419bac3"
      define_method(:install) do
        bin.install "valence"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/g4m3m4g/Valence/releases/download/v1.0.0/valence_linux_arm64.tar.gz"
      sha256 "6daec1f7bb65f67e23ce353ea146d279e109e949dc1dd2769d632a3027c2612e"
      define_method(:install) do
        bin.install "valence"
      end
    end
  end

  test do
    system "#{bin}/valence", "--help"
  end
end
